etunimi = input("Etunimi: ")
sukunimi = input("Sukunimi: ")
katuosoite = input("Katuosoite: ")
postinumeroJakaupunki = input("Postinumero ja kaupunki: ")
print(etunimi+" "+sukunimi)
print(katuosoite)
print(postinumeroJakaupunki)
